(()=>{
'use strict';
const TOTAL=25000, KEY='wedding-hub-full-2026';
const num=el=>Number(el?.value||0)||0;
const isEmergency=n=>/(emerg|imprev|reserva)/i.test(String(n||''));
let running=false;
function rows(){const list=document.getElementById('budgetList');if(!list)return[];return [...list.querySelectorAll('input[data-sv]')].map(v=>{const id=v.dataset.sv;const name=document.querySelector(`[data-sn="${CSS.escape(id)}"]`);return {v,nameInput:name,name:name?.value||'',id}})}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function ensureEmergency(){const rs=rows();if(!rs.length)return;const s=state();s.sectors=Array.isArray(s.sectors)?s.sectors:[];let em=s.sectors.find(x=>isEmergency(x.name));if(!em){em={id:'emergency',name:'Emergência / Imprevistos',value:0};s.sectors.push(em);save(s);return true}return false}
function normalize(){if(running)return;const rs=rows();if(!rs.length)return;const em=rs.find(r=>isEmergency(r.name));if(!em)return;running=true;try{const others=rs.filter(r=>r!==em);let totalOthers=others.reduce((a,r)=>a+Math.max(0,num(r.v)),0);if(totalOthers>TOTAL){const excess=totalOthers-TOTAL;const last=others[others.length-1];if(last){last.v.value=Math.max(0,num(last.v)-excess);totalOthers=others.reduce((a,r)=>a+Math.max(0,num(r.v)),0)}}em.v.value=Math.round(Math.max(0,TOTAL-totalOthers)*100)/100;const s=state();s.budget=TOTAL;s.sectors=Array.isArray(s.sectors)?s.sectors:[];rs.forEach(r=>{let x=s.sectors.find(x=>String(x.id)===String(r.id));if(!x){x={id:r.id,name:r.name,value:0};s.sectors.push(x)}x.name=r.name;x.value=num(r.v)});s.sectors=s.sectors.filter(x=>rs.some(r=>String(x.id)===String(r.id)));save(s);const max=document.getElementById('budgetInput');if(max){max.value=TOTAL;max.readOnly=true;max.disabled=true}}finally{running=false}}
function bind(){const panel=document.getElementById('budget');if(!panel||panel.__budgetFixedV3)return;panel.__budgetFixedV3=true;panel.addEventListener('input',e=>{if(e.target.matches('#budgetList input[data-sv]'))normalize();if(e.target.matches('#budgetList input[data-sn]')){const s=state(),r=rows().find(r=>r.nameInput===e.target);if(r){const x=(s.sectors||[]).find(x=>String(x.id)===String(r.id));if(x)x.name=e.target.value;save(s)}}});panel.addEventListener('change',e=>{if(e.target.matches('#budgetList input[data-sv]'))normalize();if(e.target.matches('#budgetList input[data-sn]')){const s=state(),r=rows().find(r=>r.nameInput===e.target);if(r){const x=(s.sectors||[]).find(x=>String(x.id)===String(r.id));if(x)x.name=e.target.value;save(s)}}});panel.addEventListener('click',e=>{const del=e.target.closest('[data-dels]');if(del){e.stopImmediatePropagation();const id=del.dataset.dels;const s=state();const removed=(s.sectors||[]).find(x=>String(x.id)===String(id));if(removed&&!isEmergency(removed.name)){const em=(s.sectors||[]).find(x=>isEmergency(x.name));if(em)em.value=(+em.value||0)+(+removed.value||0);s.sectors=(s.sectors||[]).filter(x=>String(x.id)!==String(id));save(s);const row=del.closest('.row');if(row)row.remove();return}return}if(e.target.id==='addSector')setTimeout(normalize,50);if(e.target.id==='saveBudget'){e.preventDefault();e.stopImmediatePropagation();const max=document.getElementById('budgetInput');if(max)max.value=TOTAL}},true);setTimeout(()=>{ensureEmergency();normalize()},100)}
window.addEventListener('load',()=>{bind();setTimeout(bind,500);setTimeout(bind,1500)});
})();
