(()=>{
'use strict';
const TOTAL=25000, KEY='wedding-hub-full-2026';
const num=el=>Number(el?.value||0)||0;
const isEmergency=n=>/(emerg|imprev|reserva)/i.test(String(n||''));
let running=false;
function rows(){const list=document.getElementById('budgetList');if(!list)return[];return [...list.querySelectorAll('input[data-sv]')].map(v=>{const id=v.dataset.sv;const name=document.querySelector(`[data-sn="${CSS.escape(id)}"]`);return {v,nameInput:name,name:name?.value||'',id}})}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function write(s){localStorage.setItem(KEY,JSON.stringify(s))}
function ensureEmergency(){const rs=rows();if(!rs.length)return;const s=state();s.sectors=Array.isArray(s.sectors)?s.sectors:[];let em=s.sectors.find(x=>isEmergency(x.name));if(!em){em={id:'emergency',name:'Emergência / Imprevistos',value:0};s.sectors.push(em);write(s);return true}return false}
function captureRowsIntoStorage(){const rs=rows();if(!rs.length)return;const s=state();s.budget=TOTAL;s.sectors=Array.isArray(s.sectors)?s.sectors:[];rs.forEach(r=>{let x=s.sectors.find(x=>String(x.id)===String(r.id));if(!x){x={id:r.id,name:r.name,value:0};s.sectors.push(x)}x.name=r.name;x.value=num(r.v)});s.sectors=s.sectors.filter(x=>rs.some(r=>String(x.id)===String(r.id)));write(s)}
function normalize(){if(running)return;const rs=rows();if(!rs.length)return;const em=rs.find(r=>isEmergency(r.name));if(!em)return;running=true;try{const others=rs.filter(r=>r!==em);let totalOthers=others.reduce((a,r)=>a+Math.max(0,num(r.v)),0);if(totalOthers>TOTAL){const last=others[others.length-1];if(last){last.v.value=Math.max(0,num(last.v)-(totalOthers-TOTAL));totalOthers=others.reduce((a,r)=>a+Math.max(0,num(r.v)),0)}}em.v.value=Math.round(Math.max(0,TOTAL-totalOthers)*100)/100;captureRowsIntoStorage();const max=document.getElementById('budgetInput');if(max){max.value=TOTAL;max.readOnly=true;max.disabled=true}}finally{running=false}}
function installStorageGuard(){if(Storage.prototype.__weddingHubBudgetGuard)return;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key===KEY&&!running){try{const incoming=JSON.parse(value);const rs=rows();if(rs.length&&Array.isArray(incoming?.sectors)){const em=rs.find(r=>isEmergency(r.name));if(em){const byId=new Map(rs.map(r=>[String(r.id),r]));incoming.budget=TOTAL;incoming.sectors=incoming.sectors.map(s=>{const r=byId.get(String(s.id));return r?{...s,name:r.name,value:num(r.v)}:s});const ids=new Set(rs.map(r=>String(r.id)));incoming.sectors=incoming.sectors.filter(s=>ids.has(String(s.id)));value=JSON.stringify(incoming)}}}catch(e){}}original.call(this,key,value)};Storage.prototype.__weddingHubBudgetGuard=true}
function bind(){const panel=document.getElementById('budget');if(!panel||panel.__budgetFixedV5)return;panel.__budgetFixedV5=true;installStorageGuard();panel.addEventListener('input',e=>{if(e.target.matches('#budgetList input[data-sv]'))normalize();if(e.target.matches('#budgetList input[data-sn]')){const s=state(),r=rows().find(r=>r.nameInput===e.target);if(r){const x=(s.sectors||[]).find(x=>String(x.id)===String(r.id));if(x)x.name=e.target.value;write(s)}}});panel.addEventListener('change',e=>{if(e.target.matches('#budgetList input[data-sv]'))normalize();if(e.target.matches('#budgetList input[data-sn]')){const s=state(),r=rows().find(r=>r.nameInput===e.target);if(r){const x=(s.sectors||[]).find(x=>String(x.id)===String(r.id));if(x)x.name=e.target.value;write(s)}}});panel.addEventListener('click',e=>{if(e.target.closest('[data-dels]'))setTimeout(()=>{ensureEmergency();normalize()},60);if(e.target.id==='addSector')setTimeout(()=>{ensureEmergency();normalize()},60);if(e.target.id==='saveBudget'){e.preventDefault();const max=document.getElementById('budgetInput');if(max)max.value=TOTAL}},false);setTimeout(()=>{ensureEmergency();normalize()},100)}
window.addEventListener('load',()=>{bind();setTimeout(bind,500);setTimeout(bind,1500)});
})();
