(()=>{
'use strict';
const TOTAL=25000, KEY='wedding-hub-full-2026';
const num=el=>Number(el?.value||0)||0;
const isEmergency=n=>/(emerg|imprev|reserva)/i.test(String(n||''));
let running=false;
function rows(){const list=document.getElementById('budgetList');if(!list)return[];return [...list.querySelectorAll('input[data-sv]')].map(v=>{const id=v.dataset.sv;const name=document.querySelector(`[data-sn="${CSS.escape(id)}"]`);return {v,nameInput:name,name:name?.value||'',id}})}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function ensureEmergency(){const rs=rows();if(!rs.length)return;const s=state();s.sectors=Array.isArray(s.sectors)?s.sectors:[];let em=s.sectors.find(x=>isEmergency(x.name));if(!em){em={id:'emergency',name:'Emergência / Imprevistos',value:0};s.sectors.push(em);save(s);return true}return false}
function normalize(){if(running)return;const rs=rows();if(!rs.length)return;running=true;try{let em=rs.find(r=>isEmergency(r.name));if(!em){running=false;return}let others=rs.filter(r=>r!==em);let totalOthers=others.reduce((a,r)=>a+Math.max(0,num(r.v)),0);let reserve=Math.max(0,25000-totalOthers);if(totalOthers>25000){const excess=totalOthers-25000;const target=others[others.length-1];if(target){target.v.value=Math.max(0,num(target.v)-excess);totalOthers=others.reduce((a,r)=>a+Math.max(0,num(r.v)),0);reserve=Math.max(0,25000-totalOthers)}}em.v.value=Math.round(reserve*100)/100;const s=state();s.budget=25000;s.sectors=Array.isArray(s.sectors)?s.sectors:[];rs.forEach(r=>{let x=s.sectors.find(x=>String(x.id)===String(r.id));if(!x){x={id:r.id,name:r.name,value:0};s.sectors.push(x)}x.name=r.name;x.value=num(r.v)});s.sectors=s.sectors.filter(x=>rs.some(r=>String(r.id)===String(x.id)));if(!s.sectors.some(x=>isEmergency(x.name)))s.sectors.push({id:'emergency',name:'Emergência / Imprevistos',value:num(em.v)});save(s);const max=document.getElementById('budgetInput');if(max){max.value=25000;max.readOnly=true;max.setAttribute('aria-readonly','true')}}finally{running=false}}
function after(){setTimeout(()=>{ensureEmergency();normalize()},0);setTimeout(normalize,80);setTimeout(normalize,250)}
function bind(){const panel=document.getElementById('budget');if(!panel||panel.__budgetFixed)return;panel.__budgetFixed=true;panel.addEventListener('input',e=>{if(e.target.matches('#budgetList input[data-sv],#budgetList input[data-sn]'))after()});panel.addEventListener('change',e=>{if(e.target.matches('#budgetList input[data-sv],#budgetList input[data-sn]'))after()});panel.addEventListener('click',e=>{if(e.target.matches('#addSector')||e.target.matches('[data-dels]'))after()});panel.addEventListener('click',e=>{if(e.target.id==='saveBudget'){const max=document.getElementById('budgetInput');if(max)max.value=25000}},true);new MutationObserver(()=>{if(!running)after()}).observe(panel,{childList:true,subtree:true});after()}
window.addEventListener('load',()=>{bind();setTimeout(bind,300);setTimeout(bind,1000)});
})();