(()=>{
'use strict';
const KEY='wedding-hub-full-2026';
const cats=['Local','Buffet','Decoração','Banda','DJ','Fotógrafo','Story maker','Pista de dança','Cabelo da noiva','Maquiagem da noiva','Cabelo e maquiagem do noivo','Roupas da noiva','Roupa do noivo','Caixa de padrinhos','Lembrancinhas','Convites','Cerimônia','Doces e bolo','Bebidas','Som e iluminação','Transporte','Lua de mel'];
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function fixStyle(){if(document.getElementById('checklistLayoutFix'))return;const s=document.createElement('style');s.id='checklistLayoutFix';s.textContent=`#check #taskList{width:100%;overflow:visible}#check #taskList .row{display:grid!important;grid-template-columns:28px minmax(0,1fr) auto auto!important;align-items:center!important;gap:10px!important;width:100%!important;padding:12px 0!important}#check #taskList .row>input[type=checkbox]{width:16px!important;margin:0!important;justify-self:center}#check #taskList .row>.grow{display:block!important;min-width:0!important;width:auto!important;flex:initial!important}#check #taskList .row>.grow .muted{white-space:normal!important;overflow-wrap:anywhere!important}#check #taskList .row>[data-edit-task],#check #taskList .row>[data-editguest],#check #taskList .row>.btn{justify-self:end;white-space:nowrap}#check #taskList .row .wf-meta{display:block!important;margin-top:3px!important}@media(max-width:650px){#check #taskList .row{grid-template-columns:24px minmax(0,1fr) auto auto!important;gap:7px!important}#check #taskList .row>.btn{padding:6px 8px!important;font-size:10px!important}}`;
document.head.appendChild(s)}
function setup(){const panel=document.getElementById('check');if(!panel)return;fixStyle();if(panel.dataset.upgraded)return;panel.dataset.upgraded='1';const form=panel.querySelector('.card');if(!form)return;const grid=form.querySelector('.grid');if(grid&&!document.getElementById('taskSector')){const field=document.createElement('div');field.className='field';field.innerHTML='<label>Setor</label><select id="taskSector">'+cats.map(c=>`<option>${c}</option>`).join('')+'</select>';grid.appendChild(field)}const add=document.getElementById('addT');if(add&&!add.dataset.sectorBound){add.dataset.sectorBound='1';add.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const name=document.getElementById('tn')?.value.trim();if(!name)return;const s=read();s.tasks=Array.isArray(s.tasks)?s.tasks:[];s.tasks.push({id:uid(),name,date:document.getElementById('td')?.value||'',done:false,category:document.getElementById('taskSector')?.value||'Local',resp:''});write(s);if(document.getElementById('tn'))document.getElementById('tn').value='';if(document.getElementById('td'))document.getElementById('td').value='';decorate()},true)}decorate();const list=document.getElementById('taskList');if(list&&!list.dataset.checkObserved){list.dataset.checkObserved='1';new MutationObserver(decorate).observe(list,{childList:true,subtree:true})}}
function decorate(){const s=read(),list=document.getElementById('taskList');if(!list)return;const tasks=s.tasks||[];list.querySelectorAll('.row').forEach(row=>{const box=row.querySelector('[data-task]');if(!box)return;const id=box.dataset.task,t=tasks.find(x=>x.id===id);if(!t)return;let meta=row.querySelector('.wf-meta');if(!meta){meta=document.createElement('div');meta.className='muted wf-meta';const grow=row.querySelector('.grow');if(grow)grow.appendChild(meta)}meta.textContent=[t.category,t.resp].filter(Boolean).join(' · ');if(!row.querySelector('[data-edit-task]')){const b=document.createElement('button');b.className='btn small';b.textContent='Editar';b.dataset.editTask=id;b.onclick=()=>edit(id);row.appendChild(b)}})}
function edit(id){const s=read(),t=(s.tasks||[]).find(x=>x.id===id);if(!t)return;const n=prompt('Tarefa',t.name);if(n===null)return;const d=prompt('Prazo (AAAA-MM-DD)',t.date||'');const c=prompt('Setor',t.category||'Local');const r=prompt('Responsável',t.resp||'');t.name=n.trim()||t.name;t.date=d||'';t.category=c||t.category||'Local';t.resp=r||'';write(s);location.reload()}
window.addEventListener('load',()=>{setup();setTimeout(setup,500)});
})();
