(()=>{
'use strict';
const KEY='wedding-hub-full-2026';
const cats=['Local','Buffet','Decoração','Banda','DJ','Fotógrafo','Story maker','Pista de dança','Cabelo da noiva','Maquiagem da noiva','Cabelo e maquiagem do noivo','Roupas da noiva','Roupa do noivo','Caixa de padrinhos','Lembrancinhas','Convites','Cerimônia','Doces e bolo','Bebidas','Som e iluminação','Transporte','Lua de mel'];
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function setup(){const panel=document.getElementById('check');if(!panel||panel.dataset.upgraded)return;panel.dataset.upgraded='1';const form=panel.querySelector('.card');if(!form)return;const grid=form.querySelector('.grid');if(grid){const field=document.createElement('div');field.className='field';field.innerHTML='<label>Setor</label><select id="taskSector">'+cats.map(c=>`<option>${c}</option>`).join('')+'</select>';grid.appendChild(field)}const add=document.getElementById('addT');if(add){add.parentElement.addEventListener('click',e=>{if(e.target!==add)return;e.preventDefault();e.stopPropagation();const name=document.getElementById('tn')?.value.trim();if(!name)return;const s=read();s.tasks=Array.isArray(s.tasks)?s.tasks:[];s.tasks.push({id:uid(),name,date:document.getElementById('td')?.value||'',done:false,category:document.getElementById('taskSector')?.value||'Local',resp:''});write(s);if(document.getElementById('tn'))document.getElementById('tn').value='';if(document.getElementById('td'))document.getElementById('td').value='';decorate()},true)}decorate();new MutationObserver(decorate).observe(document.getElementById('taskList'),{childList:true,subtree:true})}
function decorate(){const s=read(),list=document.getElementById('taskList');if(!list)return;const tasks=s.tasks||[];list.querySelectorAll('.row').forEach(row=>{const box=row.querySelector('[data-task]');if(!box)return;const id=box.dataset.task,t=tasks.find(x=>x.id===id);if(!t)return;let meta=row.querySelector('.wf-meta');if(!meta){meta=document.createElement('div');meta.className='muted wf-meta';const grow=row.querySelector('.grow');if(grow)grow.appendChild(meta)}meta.textContent=[t.category,t.resp].filter(Boolean).join(' · ');if(!row.querySelector('[data-edit-task]')){const b=document.createElement('button');b.className='btn small';b.textContent='Editar';b.dataset.editTask=id;b.onclick=()=>edit(id);row.insertBefore(b,row.lastElementChild)}})}
function edit(id){const s=read(),t=(s.tasks||[]).find(x=>x.id===id);if(!t)return;const n=prompt('Tarefa',t.name);if(n===null)return;const d=prompt('Prazo (AAAA-MM-DD)',t.date||'');const c=prompt('Setor',t.category||'Local');const r=prompt('Responsável',t.resp||'');t.name=n.trim()||t.name;t.date=d||'';t.category=c||t.category||'Local';t.resp=r||'';write(s);location.reload()}
window.addEventListener('load',()=>{setup();setTimeout(setup,500)});
})();
