(()=>{
'use strict';
const KEY='wedding-hub-full-2026';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||null}catch(e){return null}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const $=id=>document.getElementById(id);
function syncSpouses(st){const by=new Map(st.guests.map(g=>[g.id,g]));let changed=false;st.guests.forEach(g=>{if(g.spouse){const p=by.get(g.spouse);if(!p){g.spouse='';changed=true}else if(p.spouse!==g.id){p.spouse=g.id;changed=true}}});return changed}
function refresh(){location.reload()}
function editGuest(id){const st=load();const g=st.guests.find(x=>x.id===id);if(!g)return;const adults=st.guests.filter(x=>x.type==='Adulto'&&x.id!==id);const form=document.createElement('div');form.id='editGuestModal';form.style='position:fixed;inset:0;background:#0008;z-index:99999;display:flex;align-items:center;justify-content:center;padding:16px;font-family:Arial';form.innerHTML=`<div style="background:#fff;border-radius:16px;padding:20px;width:min(520px,100%);max-height:90vh;overflow:auto"><h2>Editar convidado</h2><label>Nome</label><input id="egName" value="${esc(g.name)}"><label>Grupo</label><select id="egGroup"><option>Família da noiva</option><option>Família do noivo</option><option>Amigos da noiva</option><option>Amigos do noivo</option><option>Padrinho</option><option>Madrinha</option></select><label>Tipo</label><select id="egType"><option>Adulto</option><option>Criança</option></select><label>Idade</label><input id="egAge" type="number" min="0" max="17" value="${g.age||0}"><label>RSVP</label><select id="egRsvp"><option value="pendente">Aguardando confirmação</option><option value="sim">Confirmou</option><option value="nao">Não irá</option></select><label>Responsável (criança)</label><select id="egResp"><option value="">Nenhum</option>${adults.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select><label>Cônjuge / companheiro(a)</label><select id="egSpouse"><option value="">Nenhum</option>${adults.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select><label>Observações</label><input id="egNote" value="${esc(g.note||'')}"><div style="display:flex;gap:8px;margin-top:15px"><button id="egSave" style="flex:1;padding:10px;background:#3c3324;color:#fff;border:0;border-radius:8px">Salvar</button><button id="egCancel" style="padding:10px;border:1px solid #ddd;background:#fff;border-radius:8px">Cancelar</button></div></div>`;document.body.appendChild(form);$('egGroup').value=g.group;$('egType').value=g.type;$('egRsvp').value=g.rsvp;$('egResp').value=g.responsible||'';$('egSpouse').value=g.spouse||'';$('egSave').onclick=()=>{g.name=$('egName').value.trim();g.group=$('egGroup').value;g.type=$('egType').value;g.age=g.type==='Criança'?(+$('egAge').value||0):0;g.rsvp=$('egRsvp').value;g.responsible=g.type==='Criança'?$('egResp').value:'';const old=g.spouse;const ns=g.type==='Adulto'?$('egSpouse').value:'';g.spouse=ns;if(old&&old!==ns){const o=st.guests.find(x=>x.id===old);if(o&&o.spouse===g.id)o.spouse=''}if(ns){const p=st.guests.find(x=>x.id===ns);if(p){if(p.spouse&&p.spouse!==g.id){const prev=st.guests.find(x=>x.id===p.spouse);if(prev&&prev.spouse===p.id)prev.spouse=''}p.spouse=g.id}}g.note=$('egNote').value.trim();syncSpouses(st);save(st);refresh()};$('egCancel').onclick=()=>form.remove()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function addEditButtons(){document.querySelectorAll('#guestList tbody tr').forEach(tr=>{if(tr.querySelector('[data-editguest]'))return;const sel=tr.querySelector('select[data-rsvp]');if(!sel)return;const id=sel.dataset.rsvp;const td=tr.lastElementChild;const b=document.createElement('button');b.className='btn small';b.textContent='Editar';b.dataset.editguest=id;b.onclick=()=>editGuest(id);td.prepend(b)})}
function observe(){addEditButtons();const target=$('guestList');if(target){new MutationObserver(()=>addEditButtons()).observe(target,{childList:true,subtree:true})}}
function addContractsUpgrade(){const panel=$('contracts');if(!panel||$('contractPaid'))return;const card=panel.querySelector('.card');if(!card)return;const extra=document.createElement('div');extra.className='card';extra.innerHTML=`<h3>Controle financeiro do contratado</h3><div class="grid3"><div class="field"><label>Valor contratado</label><input id="contractTotal" type="number"></div><div class="field"><label>Já pago</label><input id="contractPaid" type="number"></div><div class="field"><label>Parcelas</label><input id="contractParts" type="number" min="1" value="1"></div></div><div class="grid"><div class="field"><label>Valor de cada parcela</label><input id="contractInstallment" type="number"></div><div class="field"><label>Próximo vencimento</label><input id="contractNext" type="date"></div></div><button class="btn" id="saveContractFinancial">Salvar contratado</button>`;panel.insertBefore(extra,panel.children[1]||null);$('saveContractFinancial').onclick=()=>{const st=load();st.contracts=st.contracts||[];const supplier=$('cn').value.trim(),object=$('co').value.trim();st.contracts.push({id:Date.now().toString(36),name:object||supplier,object,supplier,value:+$('contractTotal').value||0,paid:+$('contractPaid').value||0,parts:Math.max(1,+$('contractParts').value||1),installment:+$('contractInstallment').value||0,nextDue:$('contractNext').value,status:$('cs').value,link:$('cl').value.trim()});save(st);refresh()}}
window.addEventListener('load',()=>{const st=load();if(st){if(syncSpouses(st))save(st)}observe();addContractsUpgrade()})
})();