(()=>{
'use strict';
const KEY='wedding-hub-full-2026';
const $=id=>document.getElementById(id);
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=s=>s?new Date(s+'T00:00:00').toLocaleDateString('pt-BR'):'';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let editing=null;
function normalize(p){if(!p||typeof p!=='object')p={};const total=+p.value||0,parts=Math.max(1,+p.parts||1),entry=Math.min(total,Math.max(0,+p.entry||0));if(!Array.isArray(p.installments)||p.installments.length!==parts){const old=Array.isArray(p.installments)?p.installments:[],rest=Math.max(0,total-entry),base=rest/parts;p.installments=Array.from({length:parts},(_,i)=>({id:old[i]?.id||uid(),number:i+1,value:old[i]?.value!=null?+old[i].value:(i===parts-1?rest-base*(parts-1):base),date:old[i]?.date||p.installmentDates?.[i]||'',status:old[i]?.status||'Pendente'}))}p.entry=entry;p.entryDate=p.entryDate||'';p.entryStatus=p.entryStatus||'Pendente';p.parts=parts;p.interval=p.interval||'month';return p}
function ensureStyle(){if($('payUpgradeStyle'))return;const st=document.createElement('style');st.id='payUpgradeStyle';st.textContent=`.pay-installments{margin-top:12px;border-top:1px solid var(--line);padding-top:10px}.pay-installment{display:grid;grid-template-columns:95px 1fr 145px 145px 95px;gap:7px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line);font-size:11px}.pay-installment input,.pay-installment select{padding:7px;font-size:11px}.pay-entry{font-size:11px;color:var(--muted);margin:4px 0}.pay-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.pay-totalbox{margin-top:10px;padding:9px;border-radius:8px;background:var(--bg);font-size:12px}.pay-edit-hint{font-size:11px;color:var(--muted);margin:7px 0}.pay-status{white-space:nowrap}@media(max-width:760px){.pay-installment{grid-template-columns:1fr 1fr}.pay-installment b{grid-column:1/-1}.pay-installment input,.pay-installment select{min-width:0}}`;document.head.appendChild(st)}
function calcPaid(s){return (s.payments||[]).reduce((sum,p)=>{p=normalize(p);return sum+(p.entryStatus==='Pago'?+p.entry||0:0)+(p.installments||[]).reduce((a,i)=>a+(i.status==='Pago'?+i.value||0:0),0)},0)}
function refreshSummary(){const s=read(),payments=(s.payments||[]).map(normalize),paid=calcPaid(s),committed=payments.reduce((n,p)=>n+(+p.value||0),0),budget=+s.budget||25000;const set=(id,v)=>{if($(id))$(id).textContent=money(v)};const setInput=(id,v)=>{if($(id))$(id).value=money(v)};set('hSpent',paid);set('hLeft',Math.max(0,budget-committed));setInput('budgetCommitted',committed);setInput('budgetPaid',paid);setInput('budgetLeft',Math.max(0,budget-committed))}
function sectorOptions(selected){return (read().sectors||[]).map(s=>`<option value="${esc(s.id)}" ${s.id===selected?'selected':''}>${esc(s.name)}</option>`).join('')}
function buildForm(){const card=$('payments')?.querySelector('.card');if(!card)return;const add=$('addP');if(!add)return;const old=editing?normalize((read().payments||[]).find(x=>x.id===editing)||{}):null,p=old||{};card.querySelectorAll(':scope > .grid').forEach(el=>el.style.display='none');let container=card.querySelector('.pay-upgrade-form');if(container)container.remove();const wrap=document.createElement('div');wrap.className='pay-upgrade-form';wrap.innerHTML=`<div class="grid"><div class="field"><label>Descrição</label><input id="pud" value="${esc(p.desc||'')}"></div><div class="field"><label>Setor</label><select id="pus">${sectorOptions(p.sector||'')}</select></div></div><div class="grid3"><div class="field"><label>Valor total</label><input id="puv" type="number" min="0" step="0.01" value="${p.value??''}"></div><div class="field"><label>Valor de entrada</label><input id="pue" type="number" min="0" step="0.01" value="${p.entry??0}"></div><div class="field"><label>Quantidade de parcelas</label><input id="pup" type="number" min="1" step="1" value="${p.parts||1}"></div></div><div class="grid3"><div class="field"><label>Data da entrada</label><input id="pudate" type="date" value="${p.entryDate||''}"></div><div class="field"><label>Primeiro vencimento</label><input id="pufirstdate" type="date" value="${p.installments?.[0]?.date||p.date||''}"></div><div class="field"><label>Forma de pagamento</label><select id="pum"><option ${p.method==='Pix'?'selected':''}>Pix</option><option ${p.method==='Cartão'?'selected':''}>Cartão</option><option ${p.method==='Dinheiro'?'selected':''}>Dinheiro</option><option ${p.method==='Boleto'?'selected':''}>Boleto</option><option ${p.method==='Transferência'?'selected':''}>Transferência</option></select></div></div><div class="grid"><div class="field"><label>Status da entrada</label><select id="puentrystatus"><option value="Pendente">Pendente</option><option value="Pago">Pago</option></select></div><div class="field"><label>Intervalo entre parcelas</label><select id="puinterval"><option value="month">Mensal</option><option value="15">Quinzenal (15 dias)</option></select></div></div><div class="pay-edit-hint">Cada parcela pode ser conferida e alterada individualmente antes de salvar.</div><div id="puPreview" class="pay-installments"></div><div id="puTotalBox" class="pay-totalbox"></div><div class="pay-actions"><button class="btn" id="puSave">${editing?'Salvar alterações':'Adicionar pagamento'}</button>${editing?'<button class="btn alt" id="puCancel">Cancelar</button>':''}</div>`;card.insertBefore(wrap,add);add.style.display='none';$('puentrystatus').value=p.entryStatus||'Pendente';$('puinterval').value=p.interval||'month';$('puSave').onclick=savePayment;if($('puCancel'))$('puCancel').onclick=()=>{editing=null;buildForm();render()};['puv','pue','pup','pufirstdate','puinterval'].forEach(id=>$(id)?.addEventListener('input',preview));preview()}
function preview(){const total=Math.max(0,+$('puv')?.value||0),entry=Math.min(total,Math.max(0,+$('pue')?.value||0)),parts=Math.max(1,+$('pup')?.value||1),rest=Math.max(0,total-entry),start=$('pufirstdate')?.value||'',interval=$('puinterval')?.value||'month',existing=editing?normalize((read().payments||[]).find(x=>x.id===editing)||{}).installments||[]:[];let html=`<div class="pay-entry">Entrada: <b>${money(entry)}</b>${$('pudate')?.value?' · '+fmt($('pudate').value):''}</div>`;const base=parts?rest/parts:0;for(let i=0;i<parts;i++){const fallback=i===parts-1?rest-base*(parts-1):base,old=existing[i],value=old?.value!=null?old.value:fallback;let d=old?.date||'';if(!d&&start){const dt=new Date(start+'T00:00:00');if(interval==='month')dt.setMonth(dt.getMonth()+i);else dt.setDate(dt.getDate()+15*i);d=dt.toISOString().slice(0,10)}const status=old?.status||'Pendente';html+=`<div class="pay-installment"><b>${i+1}ª parcela</b><input type="number" min="0" step="0.01" value="${(+value||0).toFixed(2)}" data-puvi="${i}"><input type="date" value="${d}" data-pudate="${i}"><select data-pustatus="${i}"><option value="Pendente" ${status==='Pendente'?'selected':''}>Pendente</option><option value="Pago" ${status==='Pago'?'selected':''}>Pago</option></select><span class="pay-status">${status==='Pago'?'✓ Pago':'Pendente'}</span></div>`}if($('puPreview'))$('puPreview').innerHTML=html;const sum=[...document.querySelectorAll('[data-puvi]')].reduce((n,e)=>n+(+e.value||0),0),diff=(total-entry)-sum;if($('puTotalBox'))$('puTotalBox').innerHTML=`Parcelas: <b>${money(sum)}</b> · restante após entrada: <b>${money(total-entry)}</b> · ${Math.abs(diff)<.01?'<span class="badge ok">Fechando exatamente</span>':'<span class="badge no">Diferença: '+money(diff)+'</span>'}`}
function savePayment(){const s=read();s.payments=Array.isArray(s.payments)?s.payments:[];const total=Math.max(0,+$('puv').value||0),entry=Math.min(total,Math.max(0,+$('pue').value||0)),parts=Math.max(1,+$('pup').value||1),old=editing?s.payments.find(p=>p.id===editing):null,installments=[...document.querySelectorAll('[data-puvi]')].map((el,i)=>({id:old?.installments?.[i]?.id||uid(),number:i+1,value:+el.value||0,date:document.querySelector(`[data-pudate="${i}"]`)?.value||'',status:document.querySelector(`[data-pustatus="${i}"]`)?.value||'Pendente'})),expected=total-entry,sum=installments.reduce((n,x)=>n+x.value,0);if(Math.abs(sum-expected)>.01){alert('As parcelas precisam somar exatamente o valor restante após a entrada.');return}const item={id:editing||uid(),desc:$('pud').value.trim()||'Pagamento',sector:$('pus').value,value:total,entry,entryDate:$('pudate').value,entryStatus:$('puentrystatus').value,parts,installments,method:$('pum').value,interval:$('puinterval').value,date:installments[0]?.date||'',status:'Pendente'};item.status=(entry<=0||item.entryStatus==='Pago')&&installments.every(i=>i.status==='Pago')?'Pago':'Pendente';if(editing){const i=s.payments.findIndex(p=>p.id===editing);if(i>=0)s.payments[i]=item}else s.payments.push(item);save(s);editing=null;render();buildForm()}
function render(){const list=$('payList');if(!list)return;const s=read();s.payments=(s.payments||[]).map(normalize);save(s);list.innerHTML=s.payments.length?s.payments.map(p=>{const paid=(p.entryStatus==='Pago'?+p.entry||0:0)+(p.installments||[]).reduce((n,i)=>n+(i.status==='Pago'?+i.value||0:0),0);return `<div class="row"><div class="grow"><b>${esc(p.desc)}</b><div class="muted">Total ${money(p.value)} · Pago ${money(paid)} · ${p.parts} parcela(s) · ${esc(p.method||'')}</div><div class="pay-entry">Entrada: ${money(p.entry||0)} · ${p.entryStatus||'Pendente'}${p.entryDate?' · '+fmt(p.entryDate):''}</div><div class="pay-installments">${(p.installments||[]).map(i=>`<div class="pay-installment"><b>${i.number}ª parcela</b><span>${money(i.value)}</span><span>Venc. ${fmt(i.date)||'sem data'}</span><span>${i.status}</span><button class="btn alt small pay-status" data-payinst="${p.id}:${i.id}">${i.status==='Pago'?'Marcar pendente':'Marcar pago'}</button></div>`).join('')}</div></div><span class="badge ${p.status==='Pago'?'ok':''}">${p.status}</span><button class="btn small" data-payedit="${p.id}">Editar</button><button class="btn small" data-pay="${p.id}">Entrada: ${p.entryStatus==='Pago'?'Paga':'Pendente'}</button><button class="btn red small" data-delp="${p.id}">Excluir</button></div>`}).join(''):'<div class="empty">Nenhum pagamento.</div>';refreshSummary()}
function hook(){ensureStyle();const payments=$('payments');if(!payments)return;const add=$('addP');if(add&&!add.dataset.upgraded){add.dataset.upgraded='1';buildForm()}render();if(!payments.dataset.payUpgrade){payments.dataset.payUpgrade='1';payments.addEventListener('click',e=>{const d=e.target.dataset;if(d.payedit){editing=d.payedit;buildForm();return}if(d.payinst){const [pid,iid]=d.payinst.split(':');const s=read(),p=s.payments.find(x=>x.id===pid),i=p?.installments?.find(x=>x.id===iid);if(i){i.status=i.status==='Pago'?'Pendente':'Pago';p.status=(p.entryStatus==='Pago'||!(p.entry||0))&&(p.installments||[]).every(x=>x.status==='Pago')?'Pago':'Pendente';save(s);render()}return}if(d.pay){const s=read(),p=s.payments.find(x=>x.id===d.pay);if(p){p.entryStatus=p.entryStatus==='Pago'?'Pendente':'Pago';p.status=(p.entryStatus==='Pago'||!(p.entry||0))&&(p.installments||[]).every(x=>x.status==='Pago')?'Pago':'Pendente';save(s);render();buildForm()}return}if(d.delp){const s=read();s.payments=s.payments.filter(x=>x.id!==d.delp);save(s);render()}})}}
window.addEventListener('wedding-hub-remote-update',()=>{render();if(editing)buildForm()});
window.addEventListener('load',()=>{setTimeout(hook,30);setTimeout(hook,700);setTimeout(hook,1600)});
})();
