(()=>{
'use strict';
const KEY='wedding-hub-full-2026';
const $=id=>document.getElementById(id);
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const money=n=>(+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=s=>s?new Date(s+'T00:00').toLocaleDateString('pt-BR'):'';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let editing=null;
function ensureStyle(){if($('payUpgradeStyle'))return;const st=document.createElement('style');st.id='payUpgradeStyle';st.textContent=`.pay-installments{margin-top:10px;border-top:1px solid var(--line);padding-top:8px}.pay-installment{display:flex;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid var(--line);font-size:11px}.pay-installment .grow{flex:1}.pay-entry{font-size:11px;color:var(--muted);margin-top:3px}.pay-edit{margin-top:8px;padding:10px;background:var(--bg);border:1px solid var(--line);border-radius:9px}.pay-edit .grid{margin-bottom:5px}.pay-installment input{padding:7px}.pay-list-head{display:flex;justify-content:space-between;align-items:center}.pay-edit-actions{display:flex;gap:6px;margin-top:7px}@media(max-width:650px){.pay-installment{align-items:flex-start;flex-wrap:wrap}.pay-installment input{min-width:110px}.pay-edit-actions .btn{flex:1}}`;
document.head.appendChild(st)}
function normalize(p){if(!Array.isArray(p.installments)){const parts=Math.max(1,+p.parts||1),total=+p.value||0,entry=Math.min(total,Math.max(0,+p.entry||0)),rest=Math.max(0,total-entry),base=rest/parts;p.installments=Array.from({length:parts},(_,i)=>({id:uid(),number:i+1,value:i===parts-1?rest-base*(parts-1):base,date:i===0?(p.date||''):p.installmentDates?.[i]||'',status:p.status||'Pendente'}));p.entry=entry;p.entryDate=p.entryDate||'';p.parts=parts}return p}
function buildForm(){const card=$('payments')?.querySelector('.card');if(!card)return;const old=$('addP');if(!old)return;const title=card.querySelector('h3');if(title)title.textContent=editing?'Editar pagamento e parcelas':'Pagamento e parcelas';const p=editing?normalize(read().payments.find(x=>x.id===editing)||{}):null;const sector=p?.sector||$('ps')?.value||'';const desc=p?.desc||'';const total=p?.value||'';const entry=p?.entry||0;const parts=p?.parts||1;const date=p?.date||'';const method=p?.method||'Pix';const status=p?.status||'Pendente';const container=card.querySelector('.pay-upgrade-form');if(container)container.remove();const wrap=document.createElement('div');wrap.className='pay-upgrade-form';wrap.innerHTML=`<div class="grid"><div class="field"><label>Descrição</label><input id="pud" value="${esc(desc)}"></div><div class="field"><label>Setor</label><select id="pus">${(read().sectors||[]).map(s=>`<option value="${esc(s.id)}" ${s.id===sector?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div></div><div class="grid3"><div class="field"><label>Valor total</label><input id="puv" type="number" min="0" step="0.01" value="${total}"></div><div class="field"><label>Valor de entrada</label><input id="pue" type="number" min="0" step="0.01" value="${entry}"></div><div class="field"><label>Quantidade de parcelas</label><input id="pup" type="number" min="1" step="1" value="${parts}"></div></div><div class="grid3"><div class="field"><label>Primeiro vencimento</label><input id="pudate" type="date" value="${date}"></div><div class="field"><label>Forma</label><select id="pum"><option ${method==='Pix'?'selected':''}>Pix</option><option ${method==='Cartão'?'selected':''}>Cartão</option><option ${method==='Dinheiro'?'selected':''}>Dinheiro</option><option ${method==='Boleto'?'selected':''}>Boleto</option><option ${method==='Transferência'?'selected':''}>Transferência</option></select></div><div class="field"><label>Status da entrada</label><select id="puentrystatus"><option value="Pendente">Pendente</option><option value="Pago">Pago</option></select></div></div><div id="puPreview" class="pay-installments"></div><div class="pay-edit-actions"><button class="btn" id="puSave">${editing?'Salvar alterações':'Adicionar pagamento'}</button>${editing?'<button class="btn alt" id="puCancel">Cancelar</button>':''}</div>`;const oldGrid=card.querySelector('.grid');if(oldGrid){card.insertBefore(wrap,oldGrid);oldGrid.style.display='none';}else card.insertBefore(wrap,old);old.style.display='none';$('puentrystatus').value=p?.entryStatus||'Pendente';$('puSave').onclick=()=>savePayment();if($('puCancel'))$('puCancel').onclick=()=>{editing=null;buildForm()};['puv','pue','pup','pudate'].forEach(id=>$(id)?.addEventListener('input',preview));preview();}
function preview(){const total=+$('puv')?.value||0,entry=+$('pue')?.value||0,parts=Math.max(1,+$('pup')?.value||1),rest=Math.max(0,total-entry),base=rest/parts,start=$('pudate')?.value||'';let html=`<div class="pay-entry">Entrada: <b>${money(Math.min(entry,total))}</b>${start?' · '+fmt(start):''}</div>`;for(let i=0;i<parts;i++){const value=i===parts-1?rest-base*(parts-1):base;let d='';if(start){const dt=new Date(start+'T00:00');dt.setMonth(dt.getMonth()+i);d=dt.toISOString().slice(0,10)}html+=`<div class="pay-installment"><b>${i+1}ª parcela</b><input type="number" step="0.01" min="0" value="${value.toFixed(2)}" data-puvi="${i}"><input type="date" value="${d}" data-pudate="${i}"></div>`}const box=$('puPreview');if(box)box.innerHTML=html}
function savePayment(){const s=read();s.payments=Array.isArray(s.payments)?s.payments:[];const total=+$('puv').value||0,entry=Math.max(0,Math.min(total,+$('pue').value||0)),parts=Math.max(1,+$('pup').value||1);const installments=[];document.querySelectorAll('[data-puvi]').forEach((el,i)=>{installments.push({id:uid(),number:i+1,value:+el.value||0,date:document.querySelector(`[data-pudate="${i}"]`)?.value||'',status:'Pendente'})});const sum=installments.reduce((a,x)=>a+x.value,0);if(Math.abs(sum-(total-entry))>.01){alert('As parcelas precisam somar exatamente o valor restante após a entrada.');return}const item={id:editing||uid(),desc:$('pud').value.trim()||'Pagamento',sector:$('pus').value,value:total,entry,entryDate:$('pudate').value,entryStatus:$('puentrystatus').value,parts,installments,method:$('pum').value,status:editing?(s.payments.find(p=>p.id===editing)?.status||'Pendente'):'Pendente',date:installments[0]?.date||''};if(editing){const i=s.payments.findIndex(p=>p.id===editing);if(i>=0)s.payments[i]=item}else s.payments.push(item);save();editing=null;location.reload()}
function render(){const list=$('payList');if(!list)return;const s=read();s.payments=(s.payments||[]).map(normalize);if(s.payments.some(p=>!p.installments))save(s);list.innerHTML=s.payments.length?s.payments.map(p=>{const entry=p.entry||0;return`<div class="row"><div class="grow"><b>${esc(p.desc)}</b><div class="muted">${money(p.value)} · ${p.parts} parcela(s) · ${esc(p.method)}${p.date?' · 1ª '+fmt(p.date):''}</div>${entry?`<div class="pay-entry">Entrada: ${money(entry)}${p.entryDate?' · '+fmt(p.entryDate):''}</div>`:''}<div class="pay-installments">${(p.installments||[]).map(i=>`<div class="pay-installment"><b>${i.number}ª parcela</b><span class="grow">${money(i.value)} · venc. ${fmt(i.date)||'sem data'}</span><span class="badge ${i.status==='Pago'?'ok':''}">${i.status}</span></div>`).join('')}</div></div><span class="badge ${p.status==='Pago'?'ok':''}">${esc(p.status)}</span><button class="btn small" data-payedit="${p.id}">Editar</button><button class="btn small" data-pay="${p.id}">Alternar</button><button class="btn red small" data-delp="${p.id}">Excluir</button></div>`}).join(''):'<div class="empty">Nenhum pagamento.</div>'}
function hook(){ensureStyle();const payments=$('payments');if(!payments)return;const add=$('addP');if(add&&!add.dataset.upgraded){add.dataset.upgraded='1';buildForm()}render();if(!payments.dataset.payUpgrade){payments.dataset.payUpgrade='1';payments.addEventListener('click',e=>{const d=e.target.dataset;if(d.payedit){editing=d.payedit;buildForm();return}if(d.pay){const s=read(),p=s.payments.find(x=>x.id===d.pay);if(p){p.status=p.status==='Pago'?'Pendente':'Pago';p.installments=(p.installments||[]).forEach(i=>i.status=p.status);save(s);render()}}if(d.delp){const s=read();s.payments=s.payments.filter(x=>x.id!==d.delp);save(s);render()}})}}
window.addEventListener('load',()=>{setTimeout(hook,30);setTimeout(hook,700)});
})();
